version: 2.1

jobs:
  build:
    docker:
      - image: node:20.10

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

     - name: Run tasks in parallel
        run: npm run dev 8080 && npm test
          

      # - run:
      #     name: run port 8080
      #     command: npm run dev 8080

      # - run:
      #     name: Run Tests
      #     command: npm test
